name: Update manifest on push
on:
  push:
    branches: [ main ]
    paths:
      - '*.json'
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Rebuild manifest
        run: |
          python - <<'EOF'
          import json, os
          files = [f for f in os.listdir('.') if f.endswith('.json') and f != 'manifest.json']
          files.sort()
          latest = max([f[:-5] for f in files], default=None)
          with open("manifest.json","w") as f:
            json.dump({"latestVersion": latest, "files": files}, f, indent=2)
          print("✅ Updated manifest with", len(files), "files")
          EOF
      - name: Commit if changed
        run: |
          if [[ -n "$(git status --porcelain manifest.json)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add manifest.json
            git commit -m "auto-update manifest"
            git push
          else
            echo "No manifest changes."
          fi
